### PR TITLE
Made app Nextcloud 13 compatible again

### LINKED ISSUE #5: nextcloud 13 compatibility
Hi,
someone have idea about nextcloud 13 compatibility, please ?

### PR DESCRIPTION
**Pull request by moonwolf-github**
This PR made application Nextcloud 13 compatible. Note i'm not PHP nor Nextcloud expert, so i might missed some niuances. This closes #5.

### CODE REVIEW

**Comment by veretcle** [comment]
I'll look into it as soon as I can

**Comment by veretcle** [comment]
Seems to be the easiest fix in the world :)

I'll add it to the mainline as soon as I can test it widely and sign it afterwards.

**Comment by moonwolf-github** [comment]
Cool (:)

**Comment by moonwolf-github** [comment]
I think you should chcek if this fix would break compatibility with Nextcloud 10 (or even 11). Not mentioning ownCloud.

Just a thought.

**Comment by veretcle** [comment]
That's exactly what I intend to do. I don't really care about ownCloud anymore, but I know a lot of people that haven't met the jump yet.

Theorically, it should not break ownCloud/NextCloud after version 11.

**Comment by moonwolf-github** [comment]
I may prepare a VM with Nextclouds tomorrow and perform simple tests. Nothing fancy of course (as i mentioned i'm not the expert) :D

**Comment by moonwolf-github** [comment]
I successfully login into Nextcloud 10.0.4 (it's in EPEL repo, so it may be popular version on CentOS/RHEL servers).

**Comment by pizzulicchio** [comment]
I'm currently using this plugin for my Nextcloud 12 and it's working well except that's impossible to edit the email settings of the user. I have assigned the email contact using the occ command.
The app, as we know, it's not compatible with nextcloud 13. My installation it's a virtual machine with vmware. I can make some test for you. Let me know

**Comment by moonwolf-github** [comment]
This PR is intended to make it compatble with Nextcloud 13.

**Comment by starmoonxp** [comment]
I stupidly edited appinfo/info.xml max compatiable version to 13. Just not work.
Looking forward to author update.

**Comment by starmoonxp** [comment]
I followed the instruction made modify to codes. User back again. Login ok in brower, But windows client and Androd client can't login.

**Comment by moonwolf-github** [comment]
On Nextcloud 10.0.4 Linux client and browser works. Android client can login but keeps asking for password on every refresh. But it happens also with original application, so it seems unrelated to this PR. Maybe it's worth opening issue in android client project? I don't see anything in server logs and i can't say where the problem is.

**Comment by starmoonxp** [comment]
I updated Android client to version 3.0. And it works again. I also updated windows client from 2.3.2 to 2.3.3. Still can't login. I think maybe it's not replated to pwauth. Waiting for a solutiion.

**Comment by starmoonxp** [comment]
It's very strange that the windows client start to work without any touch.  (version 2.3.3.1)

**Comment by starmoonxp** [comment]
Will you merge a release version to app store?

**Comment by veretcle** [comment]
It is already merged.

**Comment by starmoonxp** [comment]
I seen it. But i still upgraded to pre-2.5 and it's works fine. Thanks for your excellent work.

**Pull request merged**
